import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul>
          <li>
            <Link href="/about">Go to About</Link>
          </li>
          <li>
            <Link href="/product/1">Go to product detail</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
