import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      List Title
      <ul style={{ marginLeft: "50px" }}>
        {posts.map((i) => (
          <li key={i.id} style={{marginBottom: "10px"}}><Link href={`/post/${i.id}`}>{i.title}</Link></li>
        ))}
      </ul>
    </div>
  );
}
export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();
  return {
    props: {
      posts,
    },
  };
}
